### ISSUE TITLE
[BUG] App crashes on switching orientation in profile

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1089]
Your Rocket.Chat.Android version:
- versionCode 2009
- versionName "2.0.0-rc1"

Mobile device model and OS version: Nexus 6 - Android 7.1

### Logs
```
04-14 21:10:52.781 28703-28703/chat.rocket.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android.dev, PID: 28703
    java.lang.IllegalStateException: text_username must not be null
        at chat.rocket.android.profile.ui.ProfileFragment.enableUserInput(ProfileFragment.kt:165)
        at chat.rocket.android.profile.ui.ProfileFragment.showLoading(ProfileFragment.kt:74)
        at chat.rocket.android.profile.presentation.ProfilePresenter$loadUserProfile$1.doResume(ProfilePresenter.kt:27)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by divyanshub024** [comment]
@rafaelks I think this issue should be fixed before the release of version 2.0.
