### ISSUE TITLE
[BUG] Sometimes app crashes when you press back button when files are loading

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1378]
## Description
Crash is happening in #androidnativeapp channel and in #iosnativeapp channel  app wont crash but chatroom name will be changed to "Files"

## Steps to reproduce
open files and immediately press back button before files can be loaded.

## Logs
```
  AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: chat.rocket.android, PID: 11265
                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.addOnScrollListener(android.support.v7.widget.RecyclerView$OnScrol
                            lListener)' on a null object reference
                         E      at chat.rocket.android.files.ui.FilesFragment.showFiles(FilesFragment.kt:78)
                         E      at chat.rocket.android.files.presentation.FilesPresenter$loadFiles$1.doResume(FilesPresenter.kt:41)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
                         E      at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
                         E      at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
                         E      at android.os.Handler.handleCallback(Handler.java:873)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:193)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6642)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by philipbrito** [comment]
This issue is gone from the current app version.
