### ISSUE TITLE
build-sdk.sh

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.Android#1429]
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
rm: cannot remove '/home/mahmoud/AndroidStudioProjects/Test/Rocket.Chat.Android/app/libs/common*': No such file or directory
rm: cannot remove '/home/mahmoud/AndroidStudioProjects/Test/Rocket.Chat.Android/app/libs/core*': No such file or directory
cp: cannot stat '/home/mahmoud/AndroidStudioProjects/Test/Rocket.Chat.Kotlin.SDK/common/build/libs/common-0.1-SNAPSHOT.jar': No such file or directory
cp: cannot stat '/home/mahmoud/AndroidStudioProjects/Test/Rocket.Chat.Kotlin.SDK/core/build/libs/core-0.1-SNAPSHOT.jar': No such file or directory

**Comment by mahmodsallam** [comment]
i am using android studio 3.3 canary 1

**Comment by philipbrito** [comment]
Why creating two identical issues (https://github.com/RocketChat/Rocket.Chat.Android/issues/1428)?
What is the issue that should we reply you?

**Comment by philipbrito** [comment]
Invalid issue.
