### ISSUE TITLE
[BUG] App crashes on back press in empty message composer

### ISSUE THREAD

**Issue by shubhsherl** [RocketChat/Rocket.Chat.Android#1477]
## Description
App crashes on a back press in the empty message composer.

## Devices and Versions

Your Rocket.Chat.Android version: 2.4.0

Mobile device model and OS version: Xiaomi Redmi Note 4 - Android 7.0

## Steps to reproduce

Press backspace in the empty message Composer.
## Logs
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android.dev, PID: 30038
    java.lang.NoSuchMethodError: No static method dispatchUnhandledKeyEventPre(Landroid/view/View;Landroid/view/KeyEvent;)Z in class Landroidx/core/view/ViewCompat; or its super classes (declaration of 'androidx.core.view.ViewCompat' appears in /data/app/chat.rocket.android.dev-1/base.apk:classes7.dex)
        at androidx.appcompat.app.AppCompatDelegateImpl.dispatchKeyEvent(AppCompatDelegateImpl.java:1162)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2529)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:320)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4377)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4348)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3945)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3911)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4038)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3919)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4095)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3945)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3911)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3919)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6263)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6237)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6198)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3687)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6342)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

**Comment by divyanshub024** [comment]
It's crashing everywhere. #1474

**Comment by shubhsherl** [comment]
Oh I didn't saw that issue
