### ISSUE TITLE
[BUG] Unable to send message right after first run

### ISSUE THREAD

**Issue by twi123** [RocketChat/Rocket.Chat.Android#1587]
## Description

Unable to send text message to any room right after first app run

## Devices and Versions

Rocket.Chat.Android version: 2.5.1 from Play Market
Rocket.Chat Server version: rocketchat @ https://open.rocket.chat

Lenovo P70-A, Android 5.1
Redmi Note 4, Android 7.0 NRD90M 

## Steps to reproduce

- Remove previously installed RocketChat app, if any
- Go to Play Market and install current Rocket.Chat 2.5.1
- Use default proto/server - https://open.rocket.chat
- Authorize, using login and password
- Go to any room (or create new and go to)
- Enter some text and tap "Send"...
...
- Nothing happens*
...
- Ok, lets choose some file to upload (or just draw something) - it works as it should
- One more text messsage - nope...

Ok, go to recent apps, find Rocket.Chat and remove it.
Start Rocket.Chat app again - problem solved, text message send as expected

\* actually a NullPointer exception catched within [ChatRoomPresenter.kt (line 273)](https://github.com/RocketChat/Rocket.Chat.Android/blob/0c11cb56148abb4b75a212f08f0bee25b34c64ee/app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt#L273) when trying to set users's avatar to message `currentServer.avatarUrl(username!!)` because `username` is null...

## Logs
```
08-07 13:19:01.893 22999-22999/chat.rocket.android.dev D/ChatRoomPresenter$sendMessage: Error sending message...
    kotlin.KotlinNullPointerException
        at chat.rocket.android.chatroom.presentation.ChatRoomPresenter$sendMessage$1.doResume(ChatRoomPresenter.kt:273)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
```

**Comment by twi123** [comment]
I think, it's related to[ line 265](https://github.com/RocketChat/Rocket.Chat.Android/blob/0c11cb56148abb4b75a212f08f0bee25b34c64ee/app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt#L265), so 
replacing
`val username = userHelper.username`
with
`val username = userHelper.user()?.username`
will fix this issue...

**Comment by FaizanZahid** [comment]
i guess if app is killed and open again, the msg gets sent but it doesnt update the UI.
