### ISSUE TITLE
[BUG] Emoji cached Typeface no always initialized

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#1640]
When app is in background for some time, when getting back we get this:
```
AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: chat.rocket.android.dev, PID: 27256
                         E  kotlin.UninitializedPropertyAccessException: lateinit property cachedTypeface has not been initialized
                         E      at chat.rocket.android.emoji.EmojiRepository.getCachedTypeface$emoji_debug(EmojiRepository.kt:32)
                         E      at chat.rocket.android.emoji.internal.EmojiCategory.getTextIconFor(EmojiCategory.kt:68)
                         E      at chat.rocket.android.emoji.internal.EmojiCategory$RECENTS.textIcon(EmojiCategory.kt:14)
                         E      at chat.rocket.android.emoji.internal.EmojiPagerAdapter.getPageTitle(EmojiPagerAdapter.kt:84)
                         E      at com.google.android.material.tabs.TabLayout.populateFromPagerAdapter(TabLayout.java:1323)
                         E      at com.google.android.material.tabs.TabLayout.setPagerAdapter(TabLayout.java:1314)
                         E      at com.google.android.material.tabs.TabLayout$AdapterChangeListener.onAdapterChanged(TabLayout.java:2870)
                         E      at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:549)
                         E      at chat.rocket.android.emoji.EmojiKeyboardPopup.setupViewPager(EmojiKeyboardPopup.kt:176)
                         E      at chat.rocket.android.emoji.EmojiKeyboardPopup$onViewCreated$1.doResume(EmojiKeyboardPopup.kt:55)

```

We should check this initialization appropriately.

**Comment by leonardoaramaki** [comment]
@luciofm Is this one fixed already?
