### ISSUE TITLE
[BUG] App crashes when using custom Oath for login

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/Rocket.Chat.Android#1761]
## Description
Seems to be a bug in the new onboarding changes?
Using our custom Oath works up to a point.  It loads the webview for the Oauth provider properly, but after logging in with Oauth credentials, during the redirect to get back into the app and logged in to the server it crashes immediately.

## Log
2018-10-13 17:32:27.329 23534-23534/chat.veranda.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.veranda.android.dev, PID: 23534
    kotlin.UninitializedPropertyAccessException: lateinit property client has not been initialized
        at chat.rocket.android.authentication.loginoptions.presentation.LoginOptionsPresenter.access$getClient$p(LoginOptionsPresenter.kt:43)
        at chat.rocket.android.authentication.loginoptions.presentation.LoginOptionsPresenter$doAuthentication$1$token$1.doResume(LoginOptionsPresenter.kt:107)
        at chat.rocket.android.authentication.loginoptions.presentation.LoginOptionsPresenter$doAuthentication$1$token$1.invoke(Unknown Source:34)
        at chat.rocket.android.authentication.loginoptions.presentation.LoginOptionsPresenter$doAuthentication$1$token$1.invoke(LoginOptionsPresenter.kt:43)
        at chat.rocket.android.util.IOKt.retryIO(IO.kt:24)
        at chat.rocket.android.util.IOKt.retryIO$default(IO.kt:17)
        at chat.rocket.android.authentication.loginoptions.presentation.LoginOptionsPresenter$doAuthentication$1.doResume(LoginOptionsPresenter.kt:105)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by rondoe** [comment]
I can confirm that. "beta" branch is crashing at the same line when authenticating using my custom oauth provider. everything is working fine, when authenticating via ldap.

**Comment by rasos** [comment]
oAuth login works here with App version 2.6.1 at our set-up with an keycloak identity provider and RC 0.69.1

**Comment by ear-dev** [comment]
Yeah, I think it's working in the releases... but currently in the develop branch it crashes.  Thanks!

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/1771
