### ISSUE TITLE
[INVESTIGATE] Error Attempting to toggle a ChatRoom as favorite 

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat.Android#1814]
## Description

When attempting to favorite/unfavorite a ChatRoom, I am getting the error: `Use JsonReader.setLenient(true) to accept malformed JSON at path $`

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1
Your Rocket.Chat Server version: 0.64.2 but API all up-to-date

Mobile device model and OS version: Occurring on all devices I've checked (simulators from Android Studio)

## Logs

    2018-10-30 12:51:21.832 10290-10545/? D/null: SDK(https://chat.youngthinker.org/): Successful HTTP request: POST - https://chat.youngthinker.org/api/v1/rooms.favorite: 200 OK
    2018-10-30 12:51:21.839 10290-10290/? E/null: Error while trying to favorite/unfavorite chat room.
      chat.rocket.common.RocketChatInvalidResponseException: Use JsonReader.setLenient(true) to accept malformed JSON at path $(url='https://chat.youngthinker.org/api/v1/rooms.favorite')
        at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:76)
        at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:131)
        at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.doResume(Unknown Source:17)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
        at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
     Caused by: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
        at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:220)
        at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1031)
        at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:344)
        at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:171)
        at chat.rocket.common.model.KotshiBaseResultJsonAdapter.fromJson(KotshiBaseResultJsonAdapter.java:38)
        at chat.rocket.common.model.KotshiBaseResultJsonAdapter.fromJson(KotshiBaseResultJsonAdapter.java:13)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:36)
        at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:72)
        at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:131) 
        at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.doResume(Unknown Source:17) 
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42) 
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149) 
        at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19) 
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) 
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285) 
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152) 
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990) 
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938) 
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by rafaelks** [comment]
@TannerJuby1 Do you know what's the version of the server?

**Comment by TannerJuby1** [comment]
@rafaelks I want to say 0.62 or something but I'm not entirely for sure. I know the API has been updated to the latest versions, and favoriting a chatroom via Web or iOS work perfectly fine, just not Android. (FYI, I work for Devetry, I believe you have spoken to Daniel before about other issues.)

**Comment by rafaelks** [comment]
@TannerJuby1 0.62 is very old right now... Android is the only client using REST API to favorite/unfavorite room... this API was introduced in 0.64 (per docs: https://rocket.chat/docs/developer-guides/rest-api/rooms/favorite/#rooms-favoriteunfavorite).

Can you update and try again?

**Comment by TannerJuby1** [comment]
@rafaelks Correction, our server version is `0.64.2`.

**Comment by rafaelks** [comment]
@TannerJuby1 Do you have any logs about what's the server returning for you? If I use the app in our community server (open.rocket.chat) it doesn't show me this message on favorite/unfavorite a room.

**Comment by TannerJuby1** [comment]
@rafaelks yes I do. They are posted in the original issue. It looks like it responds with a `200` and then responds again with an error. However, even if the 200 response actually works, the channel is still not being favorited (perhaps it attempts the call twice, but then there is a race condition causing the 200 response to be pointless? I'm not sure.)

**Comment by rafaelks** [comment]
@TannerJuby1 Do you have the raw response from the server? Can you check it using some proxy or actually debugging the app? I can do that if you give me access to your server (send me an email `rafael.kellermann at rocket.chat`)

**Comment by TannerJuby1** [comment]
@rafaelks Our team was able to get it to work. Apparently, that endpoint was the only endpoint that was missing, but we never suspected it because we were getting a 200 http status code back, which we believe was caused by our multi-domain setup. Thanks for your help, sorry for wasting your time.
