### ISSUE TITLE
[BUG] Messages not shown when start new chat with user

### ISSUE THREAD

**Issue by abicur** [RocketChat/Rocket.Chat.Android#1875]
## Description

There are two bugs in video. Youtube: [video with error](https://youtu.be/hYcueLxRLT4)
1. Bug with starting new direct chat. The messages are not shown.
2. Bug on chatting with deleted user.

**The problem with new direct chat is very serious.**

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0) 3.1.1
Your Rocket.Chat Server version: (e.g. 0.63.1-develop) 0.71.1 snap installation

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")
Samsung Galaxy S8+ with Android 8.0, Samsung Galaxy S7 with Android 8.0

## Steps to reproduce
1.
-Find a user with whom you want to get a chat.
-Send mesage to him
-Message are not shown in chat and chat didnt shown in chat list. Messages don't sents to a user.
Close the Rocket.Chat app and then open it again. Chat with user and messages are shown and they are sends to user.

2.
[Video](https://youtu.be/hYcueLxRLT4?t=53)
-Delete some user with whom you have a chat. The chat will not deleted from your chat list in mobile client.
-Send message to him and close the chat.
-Open chat again and you will see "null" instead of nickname.
-If you log out in mobile app and then log in again then chat with deleted users will be deleted.

## Logs
In some cases there is an error message in Rocket.Chat server log:
`
Exception in defer callback: TypeError: Cannot read property 'lm' of undefined     at Object.markMessagesAsRead (/snap/rocketchat-server/1343/programs/server/app/app.js:60:29)     at Meteor.defer (/snap/rocketchat-server/1343/programs/server/app/app.js:11303:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at packages/meteor.js:502:25     at runWithEnvironment (packages/meteor.js:1238:24)  
`

**Comment by ihovav** [comment]
It also happens to me in all chats regardless to is it a new chat or an existing one. 
In every message I send or receive,  I do see it in the phone notifications but when openning the app I cant see it. 
If I send a message I dont see it but if I am trying to edit it I do get the text in the text box... 

App details: 
Version 3.1.1
Build 2050 - c6900816 -  play

Phone details:
Xiaomi Redmi note 4 (snapdragon,  4/64)
Android version: NRD90M 7.0
Security patch: 2018-10-01
MIUI: 10.1.1.0

**Comment by abicur** [comment]
@luciofm @filipedelimabrito May be you can comment something about this bug? Or may be I can gave you some more information about this? Thank you for your work.

**Comment by Hkarimi561** [comment]
same Issue here
