### ISSUE TITLE
Home Key -> resume app, DDP subscription failed : NoSub error

### ISSUE THREAD

**Issue by cheonjoosung** [RocketChat/Rocket.Chat.Android#197]
Your Rocket.Chat.Android version: develop - latest

When I press home button key in chat room screen, push logic work properly.

But "DDP subscription failed : NoSub Error" occurred when I relaunch rocket.chat app.

After then, I can't receive any message in the char room. 

But, the message count in Room-Lists(sidebar) is well displayed when new messages arrive.

The error log is as follows.

02-08 10:04:28.900 16423-16423/chat.rocket.android E/ROOM: onResume() Call
02-08 10:04:28.901 16423-18471/chat.rocket.android D/skia: --- SkImageDecoder::Factory returned null
02-08 10:04:28.904 16423-16423/chat.rocket.android D/RoomFragment: hasNext: true syncstate: 2
02-08 10:04:28.924 16423-17889/chat.rocket.android D/DDPClientWrapper: rpc:[a95c6324-a063-4091-91b1-ec72a0fffb9c]> UserPresence:online(null) timeout=4000
02-08 10:04:28.939 16423-18471/chat.rocket.android D/skia: --- SkImageDecoder::Factory returned null
02-08 10:04:28.942 16423-16423/chat.rocket.android V/RealmBasedConnectivityManager: ⇢ connectToServer(hostname="demo.rocket.chat")
02-08 10:04:28.942 16423-16423/chat.rocket.android V/RealmBasedConnectivityManager: ⇠ connectToServer [0ms] = rx.Single@fa15709
02-08 10:04:28.942 16423-16423/chat.rocket.android V/RocketChatService: ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat")
02-08 10:04:28.942 16423-16423/chat.rocket.android V/RocketChatService: ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@f664d3c
02-08 10:04:28.942 16423-16423/chat.rocket.android V/RocketChatWebSocketThread: ⇢ keepAlive()
02-08 10:04:28.943 16423-16423/chat.rocket.android V/RocketChatWebSocketThread: ⇠ keepAlive [0ms] = rx.Single@27f5ac5
02-08 10:04:28.948 16423-16423/chat.rocket.android D/MethodCall: MethodCall[a95c6324-a063-4091-91b1-ec72a0fffb9c] syncstate=1
02-08 10:04:28.976 16423-16423/chat.rocket.android V/RealmBasedConnectivityManager: ⇢ connectToServer(hostname="demo.rocket.chat")
02-08 10:04:28.976 16423-16423/chat.rocket.android V/RealmBasedConnectivityManager: ⇠ connectToServer [0ms] = rx.Single@2d5ce96
02-08 10:04:28.977 16423-16423/chat.rocket.android V/RocketChatService: ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat")
02-08 10:04:28.977 16423-16423/chat.rocket.android V/RocketChatService: ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@b235fed
02-08 10:04:28.977 16423-16423/chat.rocket.android V/RocketChatWebSocketThread: ⇢ keepAlive()
02-08 10:04:28.977 16423-16423/chat.rocket.android V/RocketChatWebSocketThread: ⇠ keepAlive [0ms] = rx.Single@3983e22
02-08 10:04:28.979 16423-16423/chat.rocket.android I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@b7218ee time:55348522

**02-08 14:59:59.210 28039-28671/chat.ldcc.android E/DDPSubscription: id : 8e076dd3-0e22-4a8b-859f-04d8a4dd2c32 , error : {"error":400,"reason":"Match failed","message":"Match failed [400]","errorType":"Meteor.Error"}**

**02-08 10:04:31.013 16423-17897/chat.rocket.android W/AbstractDDPDocEventSubscriber: DDP subscription failed.**
                                                                                    chat.rocket.android_ddp.DDPSubscription$NoSub$Error
                                                                                        at chat.rocket.android_ddp.DDPClientImpl.lambda$sub$16(DDPClientImpl.java:167)
                                                                                        at chat.rocket.android_ddp.DDPClientImpl$$Lambda$21.call(Unknown Source)
                                                                                        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                                                        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                                                                        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                                                                        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
                                                                                        at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                                                                                        at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:585)
                                                                                        at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:283)
                                                                                        at chat.rocket.android_ddp.rx.RxWebSocket$1$1.onMessage(RxWebSocket.java:47)
                                                                                        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:288)
                                                                                        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
                                                                                        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
                                                                                        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:261)
                                                                                        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:200)
                                                                                        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by cheonjoosung** [comment]
Additionally, registerStreamNotifyMessage(String roomId) function in StreamRoomMessageManager.java didn't work properly.
When RoomFragment resume(), that function's roomId is null.
Maybe i think that preference's change listener DO NOT work properly when app pause & resume.

**Comment by laggedHero** [comment]
That looks like what was worked out as part of #196 

After the new build, if it still happens, would you please re-open this?

Thank you.

**Comment by cheonjoosung** [comment]
Thanks. It works good.
