### ISSUE TITLE
Can not import items under chat.rocket.common

### ISSUE THREAD

**Issue by olcayertas** [RocketChat/Rocket.Chat.Android#2026]
I have cloned latest version of Rocket Chat Android and trying to build the application but it fails with import errors related to items under `chat.rocket.common`.

## To Reproduce
1. Clone the app
2. Try to build master branch

## Logs
```
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/model/MessageEntity.java:7: warning: senderId column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
public final class MessageEntity implements chat.rocket.android.db.model.BaseMessageEntity {
             ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/model/MessageEntity.java:7: warning: editedBy column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
public final class MessageEntity implements chat.rocket.android.db.model.BaseMessageEntity {
             ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/model/MessageFavoritesRelation.java:7: warning: userId column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
public final class MessageFavoritesRelation implements chat.rocket.android.db.model.BaseMessageEntity {
             ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/model/MessageMentionsRelation.java:7: warning: userId column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
public final class MessageMentionsRelation implements chat.rocket.android.db.model.BaseMessageEntity {
             ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/model/AttachmentEntity.java:7: warning: message_id column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
public final class AttachmentEntity implements chat.rocket.android.db.model.BaseMessageEntity {
             ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/MessageDao.java:71: warning: The return value includes a Pojo with a @Relation. It is usually desired to annotate this method with @Transaction to avoid possibility of inconsistent results between the Pojo and its relations. See https://developer.android.com/reference/android/arch/persistence/room/Transaction.html for details.
    public abstract chat.rocket.android.db.model.PartialMessage internalGetMessageById(@org.jetbrains.annotations.NotNull()
                                                                ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/MessageDao.java:83: warning: The return value includes a Pojo with a @Relation. It is usually desired to annotate this method with @Transaction to avoid possibility of inconsistent results between the Pojo and its relations. See https://developer.android.com/reference/android/arch/persistence/room/Transaction.html for details.
    public abstract java.util.List<chat.rocket.android.db.model.PartialMessage> internalGetMessagesByRoomId(@org.jetbrains.annotations.NotNull()
                                                                                ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/MessageDao.java:88: warning: The return value includes a Pojo with a @Relation. It is usually desired to annotate this method with @Transaction to avoid possibility of inconsistent results between the Pojo and its relations. See https://developer.android.com/reference/android/arch/persistence/room/Transaction.html for details.
    public abstract java.util.List<chat.rocket.android.db.model.PartialMessage> internalGetRecentMessagesByRoomId(@org.jetbrains.annotations.NotNull()
                                                                                ^
w: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/db/MessageDao.java:117: warning: The return value includes a Pojo with a @Relation. It is usually desired to annotate this method with @Transaction to avoid possibility of inconsistent results between the Pojo and its relations. See https://developer.android.com/reference/android/arch/persistence/room/Transaction.html for details.
    public abstract java.util.List<chat.rocket.android.db.model.PartialMessage> internalUnsetMessages();
                                                                                ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManager.java:8: error: State is not public in kotlin.collections; cannot be accessed from outside package
    private final androidx.lifecycle.MutableLiveData<kotlin.collections.State> statusLiveData = null;
                                                                       ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManager.java:9: error: State is not public in kotlin.collections; cannot be accessed from outside package
    private final java.util.concurrent.CopyOnWriteArrayList<kotlinx.coroutines.experimental.channels.Channel<kotlin.collections.State>> statusChannelList = null;
                                                                                                                               ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManager.java:10: error: State is not public in kotlin.collections; cannot be accessed from outside package
    private final kotlinx.coroutines.experimental.channels.Channel<kotlin.collections.State> statusChannel = null;
                                                                                     ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManager.java:29: error: State is not public in kotlin.collections; cannot be accessed from outside package
    public final androidx.lifecycle.MutableLiveData<kotlin.collections.State> getStatusLiveData() {
                                                                      ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManager.java:54: error: State is not public in kotlin.collections; cannot be accessed from outside package
    kotlinx.coroutines.experimental.channels.Channel<kotlin.collections.State> channel) {
                                                                       ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManager.java:59: error: State is not public in kotlin.collections; cannot be accessed from outside package
    kotlinx.coroutines.experimental.channels.Channel<kotlin.collections.State> channel) {
                                                                       ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.java:37: error: State is not public in kotlin.collections; cannot be accessed from outside package
    public final androidx.lifecycle.MutableLiveData<kotlin.collections.State> getStatus() {
                                                                      ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.java:131: error: State is not public in kotlin.collections; cannot be accessed from outside package
    private final void showConnectionState(kotlin.collections.State state) {
                                                             ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManagerKt.java:20: error: State is not public in kotlin.collections; cannot be accessed from outside package
    public static final kotlin.collections.State getState(@org.jetbrains.annotations.NotNull()
                                          ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatroom/ui/ChatRoomFragment.java:426: error: State is not public in kotlin.collections; cannot be accessed from outside package
    kotlin.collections.State state) {
                      ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatroom/presentation/ChatRoomView.java:135: error: State is not public in kotlin.collections; cannot be accessed from outside package
    kotlin.collections.State state);
                      ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.java:17: error: State is not public in kotlin.collections; cannot be accessed from outside package
    private final kotlinx.coroutines.experimental.channels.Channel<kotlin.collections.State> stateChannel = null;
                                                                                     ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.java:19: error: State is not public in kotlin.collections; cannot be accessed from outside package
    private kotlin.collections.State lastState;
                              ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public final class ChatRoomsFragment extends androidx.fragment.app.Fragment implements chat.rocket.android.chatrooms.presentation.ChatRoomsView {
             ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatroom/ui/ChatRoomFragment.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public final class ChatRoomFragment extends androidx.fragment.app.Fragment implements chat.rocket.android.chatroom.presentation.ChatRoomView, chat.rocket.android.emoji.EmojiKeyboardListener, chat.rocket.android.emoji.EmojiReactionListener, chat.rocket.android.chatroom.adapter.ChatRoomAdapter.OnActionSelected, android.graphics.drawable.Drawable.Callback {
             ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public final class ChatRoomPresenter {
             ^
e: /Users/olcayertas/Documents/Projects/Rocket.Chat.Android/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/dagger/AppComponent.java:8: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public abstract interface AppComponent {
                ^
> Task :app:kaptFossDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptFossDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:kaptFossDebugKotlin'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
	at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:16)
	at org.jetbrains.kotlin.gradle.internal.KaptWithKotlincTask.compile(KaptWithKotlincTask.kt:79)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 31 more

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:kaptFossDebugKotlin'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
	at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:16)
	at org.jetbrains.kotlin.gradle.internal.KaptWithKotlincTask.compile(KaptWithKotlincTask.kt:79)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 31 more`
```

**Comment by olcayertas** [comment]
II should have read the README first :)
