### ISSUE TITLE
[BUG] App crashes when you click channel Details button while scrolling.

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#2041]
## Describe the bug

App crashes when you click `channel Details` button in Chat while scrolling.

## Logs

```
2019-02-26 19:50:25.010 6516-6516/chat.rocket.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android.dev, PID: 6516
    java.lang.IllegalStateException: button_fab must not be null
        at chat.rocket.android.chatroom.ui.ChatRoomFragment$fabScrollListener$1.onScrolled(ChatRoomFragment.kt:262)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4961)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5117)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:710)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by dev-ritik** [comment]
I would try to make a PR on this one @divyanshub024

**Comment by divyanshub024** [comment]
@dev-ritik Sure 👍
