### ISSUE TITLE
whenever i try to connect it gives  websocket: failed to connect.

### ISSUE THREAD

**Issue by nnn-gif** [RocketChat/Rocket.Chat.Android#21]
websocket: failed to connect.
                                                                         java.lang.Exception: [Failure]
                                                                             at jp.co.crowdworks.android_ddp.ddp.DDPClientImpl.lambda$addErrorCallback$34(DDPClientImpl.java:332)
                                                                             at jp.co.crowdworks.android_ddp.ddp.DDPClientImpl.access$lambda$39(DDPClientImpl.java)
                                                                             at jp.co.crowdworks.android_ddp.ddp.DDPClientImpl$$Lambda$42.call(Unknown Source)
                                                                             at rx.Observable$27.onNext(Observable.java:8001)
                                                                             at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                             at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter.java:54)
                                                                             at rx.observers.Subscribers$5.onNext(Subscribers.java:234)
                                                                             at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:560)
                                                                             at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:258)
                                                                             at jp.co.crowdworks.android_ddp.rx.RxWebSocket$1$1.onFailure(RxWebSocket.java:44)
                                                                             at com.squareup.okhttp.ws.WebSocketCall$1.onFailure(WebSocketCall.java:107)
                                                                             at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:176)
                                                                             at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by adis-io** [comment]
It works with `demo.rocket.chat`, but not working with custom hosted server.

**Comment by adis-io** [comment]
I think I found out. 

Look at this line:
https://github.com/RocketChat/Rocket.Chat.Android.Lily/blob/0e2c2ccf1c96b23bffcf9d5835cec455aa8b7dd0/app/src/main/java/chat/rocket/android/api/ws/RocketChatWSAPI.java#L51

It tries to connect to SSL

**Comment by bhuvinay** [comment]
yes , I am also getting same error "websocket: failed to connect."
Had any one able to connect with custom server?

error logs:
9892-21260/chat.rocket.android E/Rocket.Chat.Android: websocket: failed to connect.
java.lang.Exception: [Failure]
at chat.rocket.android_ddp.DDPClientImpl.lambda$addErrorCallback$34(DDPClientImpl.java:331)
at chat.rocket.android_ddp.DDPClientImpl.access$lambda$39(DDPClientImpl.java)
at chat.rocket.android_ddp.DDPClientImpl$$Lambda$42.call(Unknown Source)
at rx.Observable$27.onNext(Observable. java:8144)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter. java:54)
at rx.observers.Subscribers$5.onNext(Subscribers.java:229)
at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:587)
at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:285)
at chat.rocket.android_ddp.rx.RxWebSocket$1$1.onFailure(RxWebSocket.java:43)
at okhttp3.ws.WebSocketCall$1.onFailure(WebSocketCall.java:104)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:140)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by adis-io** [comment]
I suppose most of users who stumbled into this issue are using non-SSL server.

So as I pointed earlier you need to change `wss` to `ws` here:
https://github.com/RocketChat/Rocket.Chat.Android.Lily/blob/0e2c2ccf1c96b23bffcf9d5835cec455aa8b7dd0/app/src/main/java/chat/rocket/android/api/ws/RocketChatWSAPI.java#L51

Update:
make sure you setup correctly nginx.

```
telnet im.example.com 80
```

**Comment by pesektomas** [comment]
Hello, I had same problem, but it reason was, that I added on begin address https://.

So I setup server address https://chat.company.cz, but setup is chat.company.cz and application works correct.
