### ISSUE TITLE
Logging in hangs

### ISSUE THREAD

**Issue by TobiasKappe** [RocketChat/Rocket.Chat.Android#223]
Your Rocket.Chat.Android version: commit `cff73c9be66a66f53b6760701d58566549c468ee` (also observed in version 1.0.5).

The app appears to hang when I try to log in. More specifically, the spinner appears to keep going indefinitely after I entered my username and password.

Running the app in the emulator, I observe the following exceptions:

```
D/StrictMode: StrictMode policy violation; ~duration=101 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.list(UnixFileSystem.java:300)
                  at java.io.File.list(File.java:1059)
                  at java.io.File.listFiles(File.java:1214)
                  at io.realm.internal.async.RealmThreadPoolExecutor.countFilesInDir(RealmThreadPoolExecutor.java:86)
                  at io.realm.internal.async.RealmThreadPoolExecutor.calculateCorePoolSize(RealmThreadPoolExecutor.java:71)
                  at io.realm.internal.async.RealmThreadPoolExecutor.<clinit>(RealmThreadPoolExecutor.java:41)
                  at io.realm.internal.async.RealmThreadPoolExecutor.newDefaultExecutor(RealmThreadPoolExecutor.java:52)
                  at io.realm.BaseRealm.<clinit>(BaseRealm.java:67)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:12)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=99 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:183)
                  at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:163)
                  at dalvik.system.DexPathList$Element.findNativeLibrary(DexPathList.java:550)
                  at dalvik.system.DexPathList.findLibrary(DexPathList.java:480)
                  at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:84)
                  at java.lang.Runtime.loadLibrary0(Runtime.java:978)
                  at java.lang.System.loadLibrary(System.java:1530)
                  at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:24)
                  at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163)
                  at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                  at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
                  at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
                  at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:59)
                  at io.realm.Realm.init(Realm.java:187)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:12)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=96 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                  at java.io.File.exists(File.java:780)
                  at android.app.ContextImpl.getDataDir(ContextImpl.java:1938)
                  at android.app.ContextImpl.getFilesDir(ContextImpl.java:531)
                  at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:223)
                  at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:407)
                  at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:402)
                  at io.realm.Realm.init(Realm.java:188)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:12)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=95 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                  at java.io.File.exists(File.java:780)
                  at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:512)
                  at android.app.ContextImpl.getFilesDir(ContextImpl.java:533)
                  at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:223)
                  at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:407)
                  at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:402)
                  at io.realm.Realm.init(Realm.java:188)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:12)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=92 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:169)
                  at java.io.File.getCanonicalPath(File.java:586)
                  at io.realm.RealmConfiguration.getCanonicalPath(RealmConfiguration.java:355)
                  at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:658)
                  at io.realm.Realm.init(Realm.java:188)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:12)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=90 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                  at java.io.File.exists(File.java:780)
                  at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:512)
                  at android.app.ContextImpl.getFilesDir(ContextImpl.java:533)
                  at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:223)
                  at io.realm.Realm.init(Realm.java:191)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:12)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=90 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:240)
                  at java.io.File.isDirectory(File.java:804)
                  at io.realm.internal.SharedRealm.initialize(SharedRealm.java:48)
                  at io.realm.Realm.init(Realm.java:191)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:12)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=90 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                  at java.io.File.exists(File.java:780)
                  at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:512)
                  at android.app.ContextImpl.getFilesDir(ContextImpl.java:533)
                  at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:223)
                  at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:407)
                  at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:402)
                  at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:394)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:14)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=89 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:169)
                  at java.io.File.getCanonicalPath(File.java:586)
                  at io.realm.RealmConfiguration.getCanonicalPath(RealmConfiguration.java:355)
                  at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:658)
                  at chat.rocket.persistence.realm.RocketChatPersistenceRealm.init(RocketChatPersistenceRealm.java:19)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:28)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/StrictMode: StrictMode policy violation; ~duration=75 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                  at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                  at java.io.File.exists(File.java:780)
                  at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:512)
                  at android.app.ContextImpl.getFilesDir(ContextImpl.java:533)
                  at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:223)
                  at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:407)
                  at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:402)
                  at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:394)
                  at chat.rocket.persistence.realm.RealmStore.getOrCreateForServerScope(RealmStore.java:45)
                  at chat.rocket.persistence.realm.models.RealmBasedServerInfo.getRealm(RealmBasedServerInfo.java:44)
                  at chat.rocket.persistence.realm.models.RealmBasedServerInfo.getServerInfoList(RealmBasedServerInfo.java:97)
                  at chat.rocket.android.service.RealmBasedConnectivityManager.getServerList(RealmBasedConnectivityManager.java:104)
                  at chat.rocket.android.RocketChatApplication.onCreate(RocketChatApplication.java:30)
                  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                  at android.app.ActivityThread.-wrap2(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

```
E/RealmBasedConnectivityManager$$Lambda$2: Disconnected
                                           chat.rocket.android.service.ServerConnectivity$DisconnectedException: Disconnected
                                               at chat.rocket.android.service.RealmBasedConnectivityManager.lambda$waitForConnected$11(RealmBasedConnectivityManager.java:199)
                                               at chat.rocket.android.service.RealmBasedConnectivityManager$$Lambda$12.call(Unknown Source)
                                               at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onSuccess(SingleOnSubscribeMap.java:66)
                                               at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:55)
                                               at rx.internal.producers.SingleProducer.request(SingleProducer.java:75)
                                               at rx.Subscriber.setProducer(Subscriber.java:211)
                                               at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
                                               at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:80)
                                               at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
                                               at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                               at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
                                               at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
                                               at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
                                               at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
                                               at chat.rocket.android.service.RealmBasedConnectivityManager.notifyConnectionLost_aroundBody2(RealmBasedConnectivityManager.java:133)
                                               at chat.rocket.android.service.RealmBasedConnectivityManager$AjcClosure3.run(RealmBasedConnectivityManager.java:1)
                                               at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                               at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                               at chat.rocket.android.service.RealmBasedConnectivityManager.notifyConnectionLost(RealmBasedConnectivityManager.java:132)
                                               at chat.rocket.android.service.RocketChatService.lambda$ensureConnectionToServer$0(RocketChatService.java:69)
                                               at chat.rocket.android.service.RocketChatService$$Lambda$1.call(Unknown Source)
                                               at rx.Single$14.call(Single.java:2241)
                                               at rx.Single$14.call(Single.java:2238)
                                               at rx.internal.operators.SingleDoOnEvent$SingleDoOnEventSubscriber.onError(SingleDoOnEvent.java:69)
                                               at rx.internal.operators.SingleDoOnEvent$SingleDoOnEventSubscriber.onError(SingleDoOnEvent.java:76)
                                               at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onError(SingleOnSubscribeMap.java:85)
                                               at rx.Single$2$1.onError(Single.java:675)
                                               at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onError(SingleOnSubscribeMap.java:85)
                                               at rx.internal.operators.SingleFromEmitter$SingleEmitterImpl.onError(SingleFromEmitter.java:99)
                                               at chat.rocket.android.service.RocketChatWebSocketThread.lambda$null$12(RocketChatWebSocketThread.java:259)
                                               at chat.rocket.android.service.RocketChatWebSocketThread$$Lambda$9.then(Unknown Source)
                                               at bolts.Task$14.run(Task.java:872)
                                               at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                               at bolts.Task.completeImmediately(Task.java:863)
                                               at bolts.Task.access$000(Task.java:32)
                                               at bolts.Task$10.then(Task.java:654)
                                               at bolts.Task$10.then(Task.java:651)
                                               at bolts.Task.runContinuations(Task.java:956)
                                               at bolts.Task.trySetError(Task.java:1011)
                                               at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
                                               at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
                                               at bolts.Task$15$1.then(Task.java:932)
                                               at bolts.Task$15$1.then(Task.java:921)
                                               at bolts.Task$14.run(Task.java:872)
                                               at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                               at bolts.Task.completeImmediately(Task.java:863)
                                               at bolts.Task.continueWith(Task.java:661)
                                               at bolts.Task.continueWith(Task.java:672)
                                               at bolts.Task$15.run(Task.java:921)
                                               at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                               at bolts.Task.completeAfterTask(Task.java:908)
                                               at bolts.Task.access$100(Task.java:32)
                                               at bolts.Task$11.then(Task.java:708)
                                               at bolts.Task$11.then(Task.java:705)
                                               at bolts.Task.runContinuations(Task.java:956)
E/RealmBasedConnectivityManager$$Lambda$2:     at bolts.Task.trySetError(Task.java:1011)
                                               at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
                                               at chat.rocket.android_ddp.DDPClientImpl.lambda$connect$7(DDPClientImpl.java:95)
                                               at chat.rocket.android_ddp.DDPClientImpl$$Lambda$10.accept(Unknown Source)
                                               at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:75)
                                               at io.reactivex.subscribers.SerializedSubscriber.onError(SerializedSubscriber.java:140)
                                               at io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutTimedSubscriber.onError(FlowableTimeoutTimed.java:257)
                                               at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:100)
                                               at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:100)
                                               at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:100)
                                               at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.checkTerminated(FlowablePublish.java:446)
                                               at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.dispatch(FlowablePublish.java:493)
                                               at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.onError(FlowablePublish.java:303)
                                               at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:268)
                                               at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:510)
                                               at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onError(FlowableCreate.java:461)
                                               at chat.rocket.android_ddp.rx.RxWebSocket$1$1.onFailure(RxWebSocket.java:44)
                                               at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
                                               at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:185)
                                               at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                               at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                               at java.lang.Thread.run(Thread.java:761)
```

```
E/RealmBasedConnectivityManager$$Lambda$2: Observable emitted no items
                                           java.util.NoSuchElementException: Observable emitted no items
                                               at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:57)
                                               at rx.internal.operators.OnSubscribeRedo$4$1.onCompleted(OnSubscribeRedo.java:321)
                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                                               at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:857)
                                               at rx.internal.operators.OnSubscribeTimerOnce$1.call(OnSubscribeTimerOnce.java:54)
                                               at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
                                               at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                               at java.lang.Thread.run(Thread.java:761)
```

Also of interest may be the following warnings:
```
W/GooglePlayServicesUtil: Google Play services out of date.  Requires 10298000 but found 9879480
[...]
W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
```

**Comment by laggedHero** [comment]
This may be related to the Apache proxy setup. Are you using it?

We'll build a test server and share what we find out.

**Comment by TobiasKappe** [comment]
Hi Tiago - thanks for getting back to me.

We are indeed using Apache as a proxy to our Rocket.Chat-instance. Let me know if you want me to test something on our end.

**Comment by tpresa** [comment]
I'm experiencing the same issue. We're using an apache proxy as well. If you need any info of our setup, please let me know.

**Comment by laggedHero** [comment]
Hello everyone,

If you're using SSL you just need to do as per this: https://github.com/RocketChat/Rocket.Chat.Docs/pull/235

It's an update to our Apache proxy setup docs.

If you are NOT using SSL there's an extra step: wait for a release of the app.
`1.0.6` will fix an issue when registering the server. https://github.com/RocketChat/Rocket.Chat.Android/pull/227

**Comment by laggedHero** [comment]
Oh yeah: @TobiasKappe @tpresa
