### ISSUE TITLE
room click -> crash : http server

### ISSUE THREAD

**Issue by cjswntjd** [RocketChat/Rocket.Chat.Android#224]
Your Rocket.Chat.Android version: lastest - develop

When click room, crash occurred. My Server uses http.

But, the issue does not happen https://demo.rocket.chat/  Server.

io.reactivex.exceptions.OnErrorNotImplementedException: The mapper function returned a null value.
                                                                            at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
                                                                            at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
                                                                            at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:75)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:207)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:392)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                         Caused by: java.lang.NullPointerException: The mapper function returned a null value.
                                                                            at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:123)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:128)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:140)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:128)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:140)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.onNext(FlowableFilter.java:118)
                                                                            at io.reactivex.internal.operators.flowable.FlowableUnsubscribeOn$UnsubscribeSubscriber.onNext(FlowableUnsubscribeOn.java:61)
                                                                            at io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.onNext(FlowableUsing.java:104)
                                                                            at hu.akarnokd.rxjava.interop.ObservableV1ToFlowableV2$ObservableSubscriber.onNext(ObservableV1ToFlowableV2.java:62)
                                                                            at io.realm.rx.RealmObservableFactory$5.call(RealmObservableFactory.java:159)
                                                                            at io.realm.rx.RealmObservableFactory$5.call(RealmObservableFactory.java:131)
                                                                            at rx.Observable.unsafeSubscribe(Observable.java:10144)
                                                                            at hu.akarnokd.rxjava.interop.ObservableV1ToFlowableV2.subscribeActual(ObservableV1ToFlowableV2.java:38)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:73)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableUnsubscribeOn.subscribeActual(FlowableUnsubscribeOn.java:33)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:33)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:35)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:41)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:33)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:35)
                                                                            at io.reactivex.Flowable.subscribe(Flowable.java:12901)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:35)
                                                                        	at io.reactivex.Flowable

**Comment by cjswntjd** [comment]
fixed
