### ISSUE TITLE
[BUG] App crashes when pressing back after changing the language

### ISSUE THREAD

**Issue by hfeky** [RocketChat/Rocket.Chat.Android#2333]
## Describe the bug
App crashes when pressing back button after changing the language from the settings.

## To Reproduce

1. Go to Settings.
2. Change language.
3. From the chats list, press back button on your device.
4. App will crash.

## Expected behavior

App should not crash.

## Logs

```
    --------- beginning of crash
2019-05-21 19:36:47.430 27117-27117/chat.rocket.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android.dev, PID: 27117
    java.lang.IllegalStateException: Fragment already added: ChatRoomsFragment{98ea8a5 #0 id=0x7f0900ea ChatRoomsFragment}
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManager.java:1916)
        at androidx.fragment.app.BackStackRecord.executePopOps(BackStackRecord.java:828)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2622)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:884)
        at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:827)
        at androidx.fragment.app.FragmentActivity.onBackPressed(FragmentActivity.java:190)
        at android.app.Activity.onKeyUp(Activity.java:2727)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2704)
        at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:334)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4823)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4492)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4662)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2449)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2028)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2019)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2426)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
```

## GIF

![Language Change Crash](https://user-images.githubusercontent.com/20887574/58123456-26910200-7c0c-11e9-99a3-701aca8879ad.gif)

## Devices and Versions
Rocket.Chat.Android version: 3.4.1 (2069)
Rocket.Chat Server version: 1.1.0-develop
Mobile device model and OS version: XPERIA XA Ultra - Android 7.0

**Comment by hfeky** [comment]
I have just noticed that this issue is already reported in issue #2323. I will close this then.
