### ISSUE TITLE
first message from app to new user

### ISSUE THREAD

**Issue by bigrender** [RocketChat/Rocket.Chat.Android#2389]
android app

When I send a message to new user, It's not working.

Might, Interner Database issue. Is there anyone who solve.?
Error Message
:hat.rocket.android.dev E/ChatRoomPresenter$sendMessage: Error sending message...
    java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:194)
        at chat.rocket.android.chatroom.presentation.ChatRoomPresenter$getTimeStampOfLastMessageInRoom$2.invokeSuspend(ChatRoomPresenter.kt:1398)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by maxim-avramenko** [comment]
The same problem

**Comment by CasaPlaysYT** [comment]
Same here

**Comment by badkaktus** [comment]
Same

**Comment by softwareDeployerSean** [comment]
same---

**Comment by softwareDeployerSean** [comment]
How to deal with it

**Comment by philipbrito** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat.Android/issues/2368
