### ISSUE TITLE
Crash when entering setting

### ISSUE THREAD

**Issue by weijia-yu** [RocketChat/Rocket.Chat.Android#2425]
## Describe the bug
Sometimes, when entering setting page, it will crash
## To Reproduce
1. In the chat list
2. click setting button
3. sometimes it won't crash, go back to chat list and re-enter for a few more times
4. if still not crash, change the language, and re-enter the setting page

## Expected behavior
It shouldn't crash

## Logs
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android.dev, PID: 2649
    java.lang.IllegalStateException: text_connection_status must not be null
        at chat.rocket.android.chatrooms.ui.ChatRoomsFragment$dismissConnectionState$2.invoke(ChatRoomsFragment.kt:77)
        at chat.rocket.android.chatrooms.ui.ChatRoomsFragment$dismissConnectionState$2.invoke(ChatRoomsFragment.kt:63)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at chat.rocket.android.chatrooms.ui.ChatRoomsFragment.getDismissConnectionState(ChatRoomsFragment.kt)
        at chat.rocket.android.chatrooms.ui.ChatRoomsFragment.access$getDismissConnectionState$p(ChatRoomsFragment.kt:63)
        at chat.rocket.android.chatrooms.ui.ChatRoomsFragment$showConnectionState$$inlined$ui$lambda$2.run(ChatRoomsFragment.kt:236)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6524)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

## Devices and Versions

Your Rocket.Chat.Android version: 3.5.0 (2073)
Your Rocket.Chat Server version: 1.3.0-rc.1

Mobile device model and OS version: Huawei Mate 9 Android 7.0

**Comment by philipbrito** [comment]
Issue was fixed (test with `3.5.0 (2074)` now). Thanks for opening. Closing...
