### ISSUE TITLE
Getting unauthorized pop up message when opening chats in public channels

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#2443]
## Description

Getting "unauthorized" pop up message when attempting to open and read in public channels that i am already in. 

I can perfectly view my joined public channels via web browser and its working fine. It also works fine on iOS devices.

However, it doesn't seem to work via the android app. 

Appreciate if you could let me know how to overcome this. thanks.

## Devices and Versions

Version: 3.5.0 (2074)
Server version: 1.1.3

**Comment by philipbrito** [comment]
@most2 Could you try logging out and in and let us know if the issue continues arriving?

**Comment by ghost** [comment]
@filipedelimabrito  hi there. nope. that did not work. still getting the same 'unauthorized' pop-up message when trying to access public channels. 
could this be a permission issue?

**Comment by dommach** [comment]
I'm facing the same issue in two androids I've tested

**Comment by apmilen** [comment]
Hi I'm also seeing an "unauthorized" error message for users trying to join existing channels with the android app. They can join on the website though. I also experienced an unauthorized error when trying to make a new channel on iOS even with admin permissions.

Server version: 1.1.1

**Comment by philipbrito** [comment]
Is any error message being displayed to you @apmilen?

**Comment by apmilen** [comment]
when I try to create a new channel on iOS I see the attached screenshot. The View Logs page only lists many instances of this error message:

```
I20190917-19:45:39.475(0) Exception in defer callback: TypeError: Cannot read property 'ls' of undefined     at Meteor.defer (server/methods/readMessages.js:26:81)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24) 
```

although it does also have one instance of this error from when we first turned it on a week ago:

```
I20190906-20:51:18.321(0) Exception from sub fullUserData id o7CxrBfNNB3xMFgYH TypeError: Cannot read property 'username' of undefined     at getFullUserData (app/lib/server/functions/getFullUserData.js:88:58)     at Subscription.<anonymous> (server/publications/fullUserData.js:10:17)     at Subscription.<anonymous> (app/lib/server/lib/debug.js:91:15)     at packages/matb33_collection-hooks.js:307:21     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)     at Session.sub (packages/ddp-server/livedata_server.js:625:12)     at packages/ddp-server/livedata_server.js:559:43 
```

I can ask the android users in my chat to send screenshots of their error messages too if you need them.

![IMG_5854](https://user-images.githubusercontent.com/2745728/65074429-d0865e00-d962-11e9-8d23-cc17bd573f48.PNG)

**Comment by reetp** [comment]
Something that is worth testing here is using the latest version of both the apps and the server as per this:

https://rocket.chat/docs/contributing/reporting-issues

>Before reporting a new issue
> ...
>    Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

Rocket server is currently v2.0.0

iOS is currently 3.5.0 standard - not sure about Test Flight
https://github.com/RocketChat/Rocket.Chat.iOS/tags

Android is currently v3.5.1-2077
https://github.com/RocketChat/Rocket.Chat.Android/tags

Also worth testing the React Native client on both as well

**Comment by brtptrs** [comment]
I'm seeing this with v3.5.1 with server v1.2.1
