### ISSUE TITLE
Cannot set hostname 

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat.Android#247]
Your Rocket.Chat.Android version: 1.0.8

Updated to 1.0.8 Android. I did have previous version working, now I need to point this updared app at a new RC server.

The app does not display the screen to set hostname, only shows login screen.

I have uninstalled and reinstalled, still do not see the hostname interface on startup

**Comment by Artraxon** [comment]
clean the cache of the app. 
normally reeinstalling should do that, but try closing the app and then cleaning the cache

**Comment by geekgonecrazy** [comment]
as @Artraxon said the only way to do this currently is by clearing the data of the app.

**Comment by aenonGit** [comment]
I'm facing the same problem, I'm trying to let the app always ask for the hostname on login. I've tried to remove the hostname by executing `removeServer(hostname)` on logout.

Result: the app prompts the user for the hostname on login but then it crashes before I can do anything:

`
05-11 12:36:44.374 14990-16296/my-app-package E/DDPClientImpl: Attempt to invoke interface method 'boolean okhttp3.WebSocket.send(java.lang.String)' on a null object reference
                                                                     java.lang.NullPointerException: Attempt to invoke interface method 'boolean okhttp3.WebSocket.send(java.lang.String)' on a null object reference
                                                                         at chat.rocket.android_ddp.rx.RxWebSocket.sendText(RxWebSocket.java:62)
                                                                         at chat.rocket.android_ddp.DDPClientImpl.sendMessage(DDPClientImpl.java:376)
                                                                         at chat.rocket.android_ddp.DDPClientImpl.ping(DDPClientImpl.java:112)
                                                                         at chat.rocket.android_ddp.DDPClient.ping(DDPClient.java:33)
                                                                         at chat.rocket.android.api.DDPClientWrapper.ping(DDPClientWrapper.java:114)
                                                                         at chat.rocket.android.service.RocketChatWebSocketThread$3.run(RocketChatWebSocketThread.java:197)
05-11 12:36:44.460 14990-16296/my.app.package E/AndroidRuntime: FATAL EXCEPTION: Thread-1537
                                                                      Process: com.voismart.connect, PID: 14990
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'io.reactivex.Flowable io.reactivex.Flowable.filter(io.reactivex.functions.Predicate)' on a null object reference
                                                                          at chat.rocket.android_ddp.DDPClientImpl.ping(DDPClientImpl.java:118)
                                                                          at chat.rocket.android_ddp.DDPClient.ping(DDPClient.java:33)
                                                                          at chat.rocket.android.api.DDPClientWrapper.ping(DDPClientWrapper.java:114)
                                                                          at chat.rocket.android.service.RocketChatWebSocketThread$3.run(RocketChatWebSocketThread.java:197)
`

**Comment by aenonGit** [comment]
anybody already working on it?

**Comment by rafaelks** [comment]
@aenonGit Yes, we're working on it already.

**Comment by aenonGit** [comment]
guys I'm really stuck at this, (been stuck for three weeks already) and I can't figure out the right steps to accomplish the task. The overall architecture is so complex and I'm always missing something! Can anyone please at least give me some hint on where to keep looking?
Besides, #272 would be really appreciated

**Comment by aenonGit** [comment]
What I've tried so far:

- Invoke **RealmBasedConnectivityManager**.removeServer(hostname) right after _logout_ method in **MethodCallHelper**; removeServer() calls DisconnectFromServerIfNeeeded which calls DisconnectFromServer. At this point I've implemented another change inside DisconnectFromServer method which clears theconnectivity list hashMap
```java
if (serviceInterface != null) {
      return serviceInterface.disconnectFromServer(hostname)
      //after disconnection from server, remove HOSTNAME key from HashMap
              .doAfterTerminate(() -> serverConnectivityList.remove(hostname));
```

- Once inside **RocketChatService**.disconnectFromServer(hostname) I've made these changes, to clear the websocket HashMap, clear the Realm, remove it, destroy the MainActivity (I've implemented the static method "getActivity") and start it again from scratch:

```java
return thread.terminate()
                //after disconnection from server, remove RCWebSocket key from HashMap
                .doAfterTerminate(() -> {
                  webSocketThreads.remove(hostname);
                  RealmHelper realmHelper = RealmStore.get(hostname);
                  realmHelper.executeTransaction(new RealmHelper.Transaction() {
                    @Override
                    public Object execute(Realm realm) throws JSONException {
                      realm.deleteAll();
                      Realm.deleteRealm(RealmStore.sStore.get(hostname));
                      return null;
                    }
                  });
                  RealmStore.sStore.remove(hostname);
                  // clears the RocketChatCache
                  MainActivity.getActivity().getSharedPreferences("cache", 0).edit().clear().commit();
                  MainActivity.getActivity().finish();
                  Intent intent = new Intent(this, MainActivity.class);
                  intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK | Intent.FLAG_ACTIVITY_NEW_TASK);
                  this.startActivity(intent);
                  stopSelf();
                });
```

Unfortunately it does not work! It correctly shows the **AddServerActivity** but then it crashes:
```java
06-15 11:14:37.415 25965-25965/chat.rocket.android E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{chat.rocket.android/chat.rocket.android.activity.MainActivity}: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. The most likely cause is that equals() and hashCode() are not overridden in the migration class: chat.rocket.persistence.realm.Migration
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. The most likely cause is that equals() and hashCode() are not overridden in the migration class: chat.rocket.persistence.realm.Migration
                                                                            at io.realm.RealmCache.validateConfiguration(RealmCache.java:276)
                                                                            at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:118)
                                                                            at io.realm.Realm.getInstance(Realm.java:227)
                                                                            at chat.rocket.persistence.realm.RealmHelper.instance(RealmHelper.java:33)
                                                                            at chat.rocket.persistence.realm.RealmHelper.executeTransactionAsync(RealmHelper.java:128)
                                                                            at chat.rocket.persistence.realm.RealmHelper.executeTransaction(RealmHelper.java:103)
                                                                            at chat.rocket.persistence.realm.models.internal.MethodCall.execute(MethodCall.java:43)
                                                                            at chat.rocket.android.api.MethodCallHelper.executeMethodCall_aroundBody0(MethodCallHelper.java:72)
                                                                            at chat.rocket.android.api.MethodCallHelper$AjcClosure1.run(MethodCallHelper.java:1)
                                                                            at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                                            at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                                            at chat.rocket.android.api.MethodCallHelper.executeMethodCall(MethodCallHelper.java:68)
                                                                            at chat.rocket.android.api.MethodCallHelper.call(MethodCallHelper.java:113)
                                                                            at chat.rocket.android.api.MethodCallHelper.setUserPresence(MethodCallHelper.java:343)
                                                                            at chat.rocket.android.activity.MainPresenter.setUserOnline(MainPresenter.java:177)
                                                                            at chat.rocket.android.activity.MainPresenter.bindView_aroundBody2(MainPresenter.java:75)
                                                                            at chat.rocket.android.activity.MainPresenter$AjcClosure3.run(MainPresenter.java:1)
                                                                            at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                                            at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                                            at chat.rocket.android.activity.MainPresenter.bindView(MainPresenter.java:64)
                                                                            at chat.rocket.android.activity.MainPresenter.bindView(MainPresenter.java:28)
                                                                            at chat.rocket.android.activity.MainActivity.onHostnameUpdated_aroundBody12(MainActivity.java:180)
                                                                            at chat.rocket.android.activity.MainActivity$AjcClosure13.run(MainActivity.java:1)
                                                                            at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                                            at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                                            at chat.rocket.android.activity.MainActivity.onHostnameUpdated(MainActivity.java:152)
                                                                            at chat.rocket.android.activity.AbstractAuthedActivity.updateHostname(AbstractAuthedActivity.java:98)
                                                                            at chat.rocket.android.activity.AbstractAuthedActivity.updateHostnameIfNeeded(AbstractAuthedActivity.java:74)
                                                                            at chat.rocket.android.activity.AbstractAuthedActivity.onCreate(AbstractAuthedActivity.java:41)
                                                                            at chat.rocket.android.activity.MainActivity.onCreate_aroundBody2(MainActivity.java:53)
                                                                            at chat.rocket.android.activity.MainActivity$AjcClosure3.run(MainActivity.java:1)
                                                                            at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                                            at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                                            at chat.rocket.android.activity.MainActivity.onCreate(MainActivity.java:53)
                                                                        	at android.ap
```

Besides, the Realm does not get cleared completely nor the schema gets deleted. Right after the MainActivity gets called again, the class_MethodCall gets populated with a record which wasn't present before
```
0	8f13002d-a872-4063-868f-beb9925cf38d	2	[null]	[null]		0	
1	d0b26e53-6d04-476a-b5ec-4ee8fcfc609a	0	UserPresence:away	[null]	[null]	4000

**Comment by matheusjardimb** [comment]
Hello @aenonGit! 
Unfortunatelly I'm working on a different issue at this time and can't help much in this one right now. 
I'll take a look on this asap.
