### ISSUE TITLE
[Crash - v3.5.2 - beta] Application can't be opened

### ISSUE THREAD

**Issue by nikolatasikj** [RocketChat/Rocket.Chat.Android#2488]
### Description:

Application can't be opened, it's crashing. Version is 3.5.2 updated from play store as beta tester. First time after update it worked, but after closing it and starting it again it's crashing. Also, when i delete cache and data and open it it's okay, but after closing not working anymore.

### Steps to reproduce:

1. Just click the icon to open app

### Expected behavior:

Application to be opened with shown list of channels

### Actual behavior:

White screen appear for 2 seconds, after that application is crashing and every background activity is closed (or it's not even started).

### Server Setup Information:

- Version of Rocket.Cha: 3.5.2 - beta 
- Operating System: Android EMUI 9.1.0

**Comment by evant89** [comment]
I have a same error.Android 9, Version of Rocket.Chat app: 3.5.2 - beta

**Comment by nikolatasikj** [comment]
Maybe this log will help you in debugging 

`2019-09-30 10:51:04.748 32343-32343/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android, PID: 32343
    java.lang.RuntimeException: Unable to create application chat.rocket.android.app.RocketChatApplication: chat.rocket.common.RocketChatInvalidResponseException: Use JsonReader.setLenient(true) to accept malformed JSON at path $(url='https://chat.wf.mk/api/v1/emoji-custom.list')
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6737)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: chat.rocket.common.RocketChatInvalidResponseException: Use JsonReader.setLenient(true) to accept malformed JSON at path $(url='https://chat.wf.mk/api/v1/emoji-custom.list')
        at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:86)
        at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:141)
        at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at chat.rocket.android.app.RocketChatApplication.loadEmojis(RocketChatApplication.kt:139)
        at chat.rocket.android.app.RocketChatApplication.onCreate(RocketChatApplication.kt:106)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
        at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:233)
        at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1051)
        at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:366)
        at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:155)
        at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:61)
        at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:47)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:36)
        at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:82)
        at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:141) 
        at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.invokeSuspend(Unknown Source:15) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241) 
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270) 
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79) 
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54) 
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1) 
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36) 
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1) 
        at chat.rocket.android.app.RocketChatApplication.loadEmojis(RocketChatApplication.kt:139) 
        at chat.rocket.android.app.RocketChatApplication.onCreate(RocketChatApplication.kt:106) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) `

**Comment by nikolatasikj** [comment]
Maybe this log will help you in debugging

`2019-09-30 10:51:04.748 32343-32343/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android, PID: 32343
    java.lang.RuntimeException: Unable to create application chat.rocket.android.app.RocketChatApplication: chat.rocket.common.RocketChatInvalidResponseException: Use JsonReader.setLenient(true) to accept malformed JSON at path $(url='(hidden url)/emoji-custom.list')
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6737)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
  `
