### ISSUE TITLE
[BUG] - App crashes on login

### ISSUE THREAD

**Issue by mihaibc** [RocketChat/Rocket.Chat.Android#2495]
## Describe the bug
The application crashes when the user is trying to connect to the server.  

## To Reproduce
1. Run the app in debug mode
2. Select "Connect with a server"
3. Enter your server URL and click "Connect"(https:// is selected)
4. Enter username and password and click "Login"
5. The app stops working.

## Expected behavior
Login process should be performed successfully 

## Logs
`/chat.rocket.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android.dev, PID: 9516
    java.lang.ClassCastException: com.squareup.moshi.internal.Util$GenericArrayTypeImpl cannot be cast to java.lang.Class
        at com.squareup.moshi.Types.getRawType(Types.java:127)
        at chat.rocket.common.internal.FallbackSealedClassJsonAdapter$Companion$ADAPTER_FACTORY$1.create(FallbackSealedClassJsonAdapter.kt:120)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:67)
        at chat.rocket.core.internal.model.KotshiLdapLoginPayloadJsonAdapter.<init>(KotshiLdapLoginPayloadJsonAdapter.kt:24)
        at chat.rocket.core.internal.KotshiCoreJsonAdapterFactory.create(KotshiCoreJsonAdapterFactory.kt:214)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:71)
        at chat.rocket.core.internal.rest.LoginKt$loginWithLdap$2.invokeSuspend(Login.kt:99)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)`

## Devices and Versions
Rocket.Chat.Android 

- version-name: 3.5.2 
- version-code: 2080

Rocket.Chat Server version: 1.3.2

This issue was reproduced on 

- Samsung Galaxy S8+ with Android 9
- Pixel 3 Android Studio Emulator with Android 10(API 29) 

## Additional context
Same behavior was tested with version 3.5.1(2077) that is available on Play Store and everything works OK.

**Comment by gerroon** [comment]
I have the same problem on LIneageOs 7.1

**Comment by azzaxx2** [comment]
Same for me.

**Comment by cuong-ntq** [comment]
I rollback to 3.5.1 version on master branch. And it work fine

**Comment by azzaxx2** [comment]
> I rollback to 3.5.1 version on master branch. And it work fine

Done same. Can't even build project.
What about kotlin.sdk? What version of it do you use?

**Comment by cuong-ntq** [comment]
> > I rollback to 3.5.1 version on master branch. And it work fine
> 
> Done same. Can't even build project.
> What about kotlin.sdk? What version of it do you use?

Remove build folder from Android project, SDK project and rebuild. It will regenerate all libs.

**Comment by azzaxx2** [comment]
> > > I rollback to 3.5.1 version on master branch. And it work fine
> > 
> > 
> > Done same. Can't even build project.
> > What about kotlin.sdk? What version of it do you use?
> 
> Remove build folder from Android project, SDK project and rebuild. It will regenerate all libs.

Did it. And it's works! Thank you!

**Comment by reetp** [comment]
This repo is now deprecated and issues will not get fixed here.

Android 4.x is React Native. Please open in the correct repo

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

Please move to the React Native Client

https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by azzaxx2** [comment]
Why did you leave the project with an error? -_-

**Comment by mobin1623** [comment]
Im having the same issue , can anyone suggest any steps to follow.

**Comment by diegolmello** [comment]
@mobin1623 Make sure you're running the latest version on Google Play (4.5.2 currently).
If it keeps happening, open an issue on the new repo: https://github.com/RocketChat/Rocket.Chat.ReactNative
Thanks.
