### ISSUE TITLE
Google Login for the 1st time gives 500 internal server error on username registering screen

### ISSUE THREAD

**Issue by ssachan** [RocketChat/Rocket.Chat.Android#2542]
The option selected was to join a workspace. 
When logging in for the first time via google login, user is asked to set username. 
Once he clicks Register, a 500 internal server error is shown
This error doesnt happen if the user is already registered via the web interface. 
It happens only for first time registration via mobile. 

## Logs
I20200430-09:28:14.300(0) Exception while invoking method 'setUsername' TypeError: Cannot destructure property joinDefaultChannelsSilenced of 'undefined' or 'null'. at MethodInvocation.setUsername (app/lib/server/methods/setUsername.js:13:9) at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34) at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12) at packages/ddp-server/livedata_server.js:719:19 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12) at packages/ddp-server/livedata_server.js:717:46 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12) at packages/ddp-server/livedata_server.js:715:46 at new Promise (<anonymous>) at Session.method (packages/ddp-server/livedata_server.js:689:23) at packages/ddp-server/livedata_server.js:559:43

## Screenshots attached
![WhatsApp Image 2020-04-30 at 12 34 53 AM](https://user-images.githubusercontent.com/1888803/80862224-ed249b80-8c90-11ea-80c6-f48da4887435.jpeg)

**Comment by PPACI** [comment]
Got exactly the same, but on iOS and for the 1st login on Azure.
