### ISSUE TITLE
Disable acceleration 3D

### ISSUE THREAD

**Issue by m4druga** [RocketChat/Rocket.Chat.Android#31]
My cellphone doesn't support acceleration 3D and the app closes soon after execution. Have some way to disable the animations that need acceleration 3D?

09-02 11:52:22.323 29796-30424/chat.rocket.android E/AndroidRuntime: FATAL EXCEPTION: RecordFBO GL render
Process: chat.rocket.android, PID: 29796
Theme: themes:{}
java.lang.RuntimeException: eglCreatePbufferSurface: EGL error: 0x3005
                                                                         at io.repro.android.grafika.gles.b.a(Unknown Source)
                                                                         at io.repro.android.grafika.gles.b.a(Unknown Source)
                                                                         at io.repro.android.grafika.gles.c.a(Unknown Source)
                                                                         at io.repro.android.grafika.gles.g.<init>(Unknown Source)
                                                                         at io.repro.android.p$b.e(Unknown Source)
                                                                         at io.repro.android.p$b.run(Unknown Source)`

**Comment by YusukeIwaki** [comment]
This issue may be caused by Repro SDK, which is removed in #36
