### ISSUE TITLE
Not Show Memer List

### ISSUE THREAD

**Issue by naser9878** [RocketChat/Rocket.Chat.Android#310]
Error 
import dalvik.system.CloseGuard; in CursorWindow not suport Api 25

```
Your Rocket.Chat.Android version: (make sure you are running the latest)
`06-08 05:37:40.412 2222-2234/chat.rocket.android E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                   at android.database.**CursorWindow**.<init>(CursorWindow.java:111)
                                                                   at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
                                                                   at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
                                                                   at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                                   at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
                                                                   at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
                                                                   at com.google.android.gms.internal.zzatv.zza(Unknown Source)
                                                                   at com.google.android.gms.internal.zzatv.zza(Unknown Source)
                                                                   at com.google.android.gms.internal.zzaul.zzc(Unknown Source)
                                                                   at com.google.android.gms.internal.zzauj.zzb(Unknown Source)
                                                                   at com.google.android.gms.internal.zzauj.zza(Unknown Source)
                                                                   at com.google.android.gms.internal.zzauj$8.run(Unknown Source)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at com.google.android.gms.internal.zzaud$zzd.run(Unknown Source)
06-08 05:37:40.412 2222-2234/chat.rocket.android E/StrictMode: Finalizing a Cursor that has not been deactivated or closed. database = /data/data/chat.rocket.android/databases/google_app_measurement_local.db, table = null, query = select count(1) from messages
                                                               android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                   at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:98)
                                                                   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
                                                                   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                   at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
                                                                   at com.google.android.gms.internal.zzatv.zza(Unknown Source)
                                                                   at com.google.android.gms.internal.zzatv.zza(Unknown Source)
                                                                   at com.google.android.gms.internal.zzaul.zzc(Unknown Source)
                                                                   at com.google.android.gms.internal.zzauj.zzb(Unknown Source)
                                                                   at com.google.android.gms.internal.zzauj.zza(Unknown Source)
                                                                   at com.google.android.gms.internal.zzauj$8.run(Unknown Source)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at com.google.android.gms.internal.zzaud$zzd.run(Unknown Source)
`
```

**Comment by matheusjardimb** [comment]
Hello @naserbagheri, thanks for your interest in helping us!

But could you go a little deeper in what exactly have happened or should have happened? :)

Thanks!

**Comment by rafaelks** [comment]
Fixed already!
