### ISSUE TITLE
[QUESTION] I'm trying to login but I am getting an error when I was clicked to sign in.(at Localhost)

### ISSUE THREAD

**Issue by sonermercimek** [RocketChat/Rocket.Chat.Android#687]
01-08 09:12:58.900 15620-15620/chat.rocket.android E/UncaughtException: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                                                                            at android.os.Handler.handleCallback(Handler.java:790)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                         C**aused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/KotlinPackage;
                                                                            at chat.rocket.android.widget.helper.AvatarHelper.<clinit>(AvatarHelper.kt:114)
                                                                            at chat.rocket.android.renderer.UserRenderer.showAvatar(UserRenderer.kt:18)
                                                                            at chat.rocket.android.fragment.sidebar.SidebarMainFragment.onRenderCurrentUser(SidebarMainFragment.java:291)
                                                                            at chat.rocket.android.fragment.sidebar.SidebarMainFragment.show(SidebarMainFragment.java:265)
                                                                            at chat.rocket.android.fragment.sidebar.SidebarMainPresenter.lambda$bindView$0$SidebarMainPresenter(SidebarMainPresenter.java:80)
                                                                            at chat.rocket.android.fragment.sidebar.SidebarMainPresenter$$Lambda$1.accept(Unknown Source:0)
                                                                            at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:62)
                                                                            at com.tspoon.traceur.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:64)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)**
                                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                            at android.os.Handler.handleCallback(Handler.java:790) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                            at android.os.Looper.loop(Looper.java:164) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
01-08 09:12:58.900 15620-15620/chat.rocket.android E/UncaughtException: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.KotlinPackage" on path: DexPathList[[zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/base.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_dependencies_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_0_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_1_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_2_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_3_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_4_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_5_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_6_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_7_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_8_apk.apk", zip file "/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/base.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/chat.rocket.android-5v_t2OaFarZUVXY-PwJCCg==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                            	... 18 more

**Comment by rafaelks** [comment]
@sonermercimek What branch are you using?

**Comment by sonermercimek** [comment]
@rafaelks Hi Rafael.Firstly,thank you so much.
 We downloaded  V.1.1.0 from releases. We don't use branch. 

You can see the error on this link
https://imgur.com/esJeH7N

I think, maybe something missing about kotlin package.What do you think about this problem?

**Comment by sonermercimek** [comment]
up up

**Comment by rafaelks** [comment]
Issue is not valid in version 2.0.0 anymore.

**Comment by ksmirenko** [comment]
Hi. Sorry to bother you, but I am having a similar issue in another project. Do you remember what exactly helped fix the problem with unresolved KotlinPackage?

**Comment by imrankst1221** [comment]
I got the same issue, https://stackoverflow.com/questions/61676058/java-lang-noclassdeffounderror-failed-resolution-of-lkotlin-kotlinpackage?noredirect=1#comment109095530_61676058
