### ISSUE TITLE
Memory Leak when trying upload file.

### ISSUE THREAD

**Issue by joeljacobdev** [RocketChat/Rocket.Chat.Android#749]
Memory Leak in App Caused when I tried to upload a file. I think it is caused when we try to upload A file which is more than the allowed size or file of an unsupported format.

- Your Rocket.Chat.Android app version: 1.1.0-DEBUG
- Your Rocket.Chat server version: version used by open.rocket.chat
- Device model (or emulator) you're running with: Lenovo K6 Power

*Log*

```
  02-15 16:22:13.561 27811-29013/chat.rocket.android E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'response.body().close()' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.lang.reflect.Method.invoke(Native Method)
        at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:329)
        at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:144)
        at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
        at okhttp3.RealCall.execute(RealCall.java:73)
        at chat.rocket.android.service.observer.FileUploadingToUrlObserver.lambda$onUpdateResults$4$FileUploadingToUrlObserver(FileUploadingToUrlObserver.java:171)
        at chat.rocket.android.service.observer.FileUploadingToUrlObserver$$Lambda$4.then(Unknown Source)
        at bolts.Task$15.run(Task.java:917)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.continueWithTask(Task.java:715)
        at bolts.Task.continueWithTask(Task.java:726)
        at bolts.Task$13.then(Task.java:818)
        at bolts.Task$13.then(Task.java:806)
        at bolts.Task$15.run(Task.java:917)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.access$100(Task.java:32)
        at bolts.Task$11.then(Task.java:708)
        at bolts.Task$11.then(Task.java:705)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.access$000(Task.java:32)
        at bolts.Task$10.then(Task.java:654)
        at bolts.Task$10.then(Task.java:651)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.access$000(Task.java:32)
        at bolts.Task$10.then(Task.java:654)
        at bolts.Task$10.then(Task.java:651)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.continueWith(Task.java:661)
        at bolts.Task.continueWith(Task.java:672)
        at bolts.Task$15.run(Task.java:921)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.access$100(Task.java:32)
        at bolts.Task$11.then(Task.java:708)
        at bolts.Task$11.then(Task.java:705)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
02-15 16:22:13.567 27811-29013/chat.rocket.android E/StrictMode:     at bolts.Task.continueWith(Task.java:661)
        at bolts.Task.continueWith(Task.java:672)
        at bolts.Task$15.run(Task.java:921)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.access$100(Task.java:32)
        at bolts.Task$11.then(Task.java:708)
        at bolts.Task$11.then(Task.java:705)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.continueWith(Task.java:661)
        at bolts.Task.continueWith(Task.java:672)
        at bolts.Task$15.run(Task.java:921)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.access$100(Task.java:32)
        at bolts.Task$11.then(Task.java:708)
        at bolts.Task$11.then(Task.java:705)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.continueWith(Task.java:661)
        at bolts.Task.continueWith(Task.java:672)
        at bolts.Task$15.run(Task.java:921)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.access$100(Task.java:32)
        at bolts.Task$11.then(Task.java:708)
        at bolts.Task$11.then(Task.java:705)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.continueWith(Task.java:661)
        at bolts.Task.continueWith(Task.java:672)
        at bolts.Task$15.run(Task.java:921)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.access$100(Task.java:32)
        at bolts.Task$11.then(Task.java:708)
        at bolts.Task$11.then(Task.java:705)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at chat.rocket.android_ddp.DDPClientImpl.lambda$rpc$31$DDPClientImpl(DDPClientImpl.java:317)
        at chat.rocket.android_ddp.DDPClientImpl$$Lambda$37.accept(Unknown Source)
        at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:62)
        at com.tspoon.traceur.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:64)
        at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
        at io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutTimedSubscriber.onNext(FlowableTimeoutTimed.java:221)
        at com.tspoon.traceur.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:64)
        at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
        at com.tspoon.traceur.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:64)
02-15 16:22:13.568 27811-29013/chat.rocket.android E/StrictMode:     at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
        at com.tspoon.traceur.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:64)
        at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
        at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
        at com.tspoon.traceur.FlowableOnAssembly$OnAssemblyConditionalSubscriber.onNext(FlowableOnAssembly.java:101)
        at com.tspoon.traceur.FlowableOnAssembly$OnAssemblyConditionalSubscriber.onNext(FlowableOnAssembly.java:101)
        at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.dispatch(FlowablePublish.java:528)
        at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.onNext(FlowablePublish.java:229)
        at com.tspoon.traceur.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:64)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:521)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:445)
        at chat.rocket.android_ddp.rx.RxWebSocket$1.onMessage(RxWebSocket.java:55)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
02-15 16:22:26.862 27811-27811/chat.rocket.android V/unknown:AbstractDraweeController: controller fa43070 null -> 232: initialize
    controller 704249e 223: setHierarchy: null
    controller fa43070 232: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@484a8a4
02-15 16:22:31.319 27811-27905/chat.rocket.android D/DDPClient: ping[9b3d19b1-549c-4b7f-a7bb-cc399670d7c4] >
02-15 16:22:31.680 27811-29446/chat.rocket.android D/DDPClientImpl: pong[9b3d19b1-549c-4b7f-a7bb-cc399670d7c4] <
02-15 16:22:51.319 27811-27905/chat.rocket.android D/DDPClient: ping[10cf520a-a79c-4c01-b66e-259bf54c3675] >
02-15 16:22:51.703 27811-29446/chat.rocket.android D/DDPClientImpl: pong[10cf520a-a79c-4c01-b66e-259bf54c3675] <
```

Complete Log at https://pastebin.com/tS8ec6gZ

I like to solve this bug. Please point me in the right direction. I think we can fix this by closing response.

**Comment by rafaelks** [comment]
Closing this issue in favor of our milestone 2.0.0 that is almost completed. More information here: https://github.com/RocketChat/Rocket.Chat.Android/milestone/6
