### ISSUE TITLE
[BUG] Crash on switching between Chats and Profile

### ISSUE THREAD

**Issue by abdulwd** [RocketChat/Rocket.Chat.Android#934]
Your Rocket.Chat.Android version: **2.0.0-alpha1**

Mobile device model and OS version: Redmi Note 3 - Android 6.0.1

Steps to reproduce:
- Switch to **Profile** using the navigation drawer.
- Press the checkmark button in the toolbar.
- Switch back to **Chats** using the navigation drawer before the loading animation disappears.

Reproducing the bug is difficult as one needs to switch from **Profile** to **Chats** quickly.
The app crashes with the following stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: chat.rocket.android.dev, PID: 16094
                                                                         java.lang.IllegalStateException: view_loading must not be null
                                                                             at chat.rocket.android.profile.ui.ProfileFragment.hideLoading(ProfileFragment.kt:77)
                                                                             at chat.rocket.android.profile.presentation.ProfilePresenter$updateUserProfile$1.doResume(ProfilePresenter.kt:66)
                                                                             at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                             at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
                                                                             at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                                                                             at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
                                                                             at android.os.Handler.handleCallback(Handler.java:742)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:157)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5555)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

**Comment by leonardoaramaki** [comment]
@abdulwd this is a known issue. We're going to have it fixed on next release.

**Comment by abdulwd** [comment]
@leonardoaramaki I searched the issue tracker and was unable to find it. My bad. 
Should I close this issue? :)

**Comment by leonardoaramaki** [comment]
Sorry, it's not on the issue tracker indeed. I just meant we are aware about that. :)
You can keep it open

**Comment by divyanshub024** [comment]
This issue is solved and can be closed now.
