### ISSUE TITLE
[BUG] App crashes on sending contacts as attachments

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#935]
Rocket.Chat.Android version: (make sure you are running the latest)

2.0.0-alpha1

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

Nexus 6 - Android 7.1

## Description
App crashes while selecting contacts in file attachments.
If contacts support is not there then the option should not be there to select.

### Logs
```
           CursorWindow  E  Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 36 columns.
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: chat.rocket.android.dev, PID: 26031
                         E  java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                         E      at android.database.CursorWindow.nativeGetString(Native Method)
                         E      at android.database.CursorWindow.getString(CursorWindow.java:438)
                         E      at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                         E      at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                         E      at chat.rocket.android.util.extensions.UriKt.getFileName(Uri.kt:23)
                         E      at chat.rocket.android.chatroom.domain.UriInteractor.getFileName(UriInteractor.kt:15)
                         E      at chat.rocket.android.chatroom.presentation.ChatRoomPresenter$uploadFile$1$fileName$1.doResume(ChatRoomPresenter.kt:128)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                         E      at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                         E      at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
                         E      at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
                         E      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:256)
                         E      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1123)
                         E      at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1961)
                         E      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1909)
                         E      at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:128)

```

**Comment by Piyush01Bhatt** [comment]
i would like to work on this issue so can some tell me in which directory i can find the class which has the code for above bug

**Comment by divyanshub024** [comment]
@Piyush01Bhatt contacts are not supported now. Contacts will be filtered out of attachments.
