### ISSUE TITLE
[BUG] App crashes when you switch from chat to settings while loading

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#952]
Rocket.Chat.Android version: (make sure you are running the latest)

2.0.0-alpha1

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

Nexus 6 - Android 7.1

App crashes when you switch from chats to settings while loading is going on

**Logs**

```
AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: chat.rocket.android.dev, PID: 22869
                         E  java.lang.IllegalStateException: view_loading must not be null
                         E      at chat.rocket.android.chatrooms.ui.ChatRoomsFragment.hideLoading(ChatRoomsFragment.kt:110)
                         E      at chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter$loadChatRooms$1.doResume(ChatRoomsPresenter.kt:53)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
                         E      at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                         E      at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
                         E      at android.os.Handler.handleCallback(Handler.java:751)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:154)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6119)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by samrmur** [comment]
Likely related to #915

**Comment by leonardoaramaki** [comment]
Thanks for reporting @samrmur but this issue is simpler than that I think. It should be fixed on next release.

**Comment by rafaelks** [comment]
@divyanshub024 Can you confirm if this is already fixed please?

**Comment by divyanshub024** [comment]
@rafaelks This issue is now fixed!

**Comment by divyanshub024** [comment]
closing the issue as it is fixed!
