### ISSUE TITLE
[URGENT][BUG] Any OAuth authentication with non-registered user results in a crash

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#981]
@filipedelimabrito From Fabric, I believe this is the crash:

```
LoginPresenter.kt line 263
chat.rocket.android.authentication.login.presentation.LoginPresenter.saveAccount

Fatal Exception: kotlin.KotlinNullPointerException
       at chat.rocket.android.authentication.login.presentation.LoginPresenter.saveAccount(LoginPresenter.kt:263)
       at chat.rocket.android.authentication.login.presentation.LoginPresenter$doAuthentication$1.doResume(LoginPresenter.kt:219)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
       at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5763)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by rafaelks** [comment]
@filipedelimabrito Renamed the issue to the crash reason.
